language: java

jdk:
  - openjdk8

notifications:
  email: false

before_install:
  - chmod +x mvnw

script:
  - export TZ=Asia/Shanghai
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash)